version: "3.4"

services:
  postgresql:
    image: postgres:11.12
    container_name: "rl_postgresql"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=open
      - POSTGRES_USER=postgres
      - POSTGRES_DB=JwtTestDb
      - POSTGRES_PORT=5432
      # - PGDATA="/data/postgres"  # PGDATA: /data/postgres
    volumes:
      - postgresql-data-11.12:/var/lib/postgresql/data
    networks:
      - corecmd_playground_network
    # restart: unless-stopped

networks:
  corecmd_playground_network:

volumes:
  postgresql-data-11.12:
